export const LOGIN_VIEW_STATE = 'LOGIN_VIEW_STATE';
export const ARTICLES_VIEW_STATE = 'ARTICLES_VIEW_STATE';
export const REMEMBER_ARTICLES_VIEW_STATE = 'REMEMBER_ARTICLES_VIEW_STATE';
export const UPDATE_ARTICLE_VIEW_STATE = 'UPDATE_ARTICLE_VIEW_STATE';
export const DELETE_ARTICLE_VIEW_STATE = 'DELETE_ARTICLE_VIEW_STATE';
